/**
 * Bundled fun facts shown while pi is working.
 *
 * Kept short (<120 chars each) so the working-message line wraps cleanly
 * in narrow terminals. Mix of science, history, animals, language, etc.
 * No two facts start with the same prefix to keep the rotation feeling varied.
 */
export const BUNDLED_FACTS: readonly string[] = [
	"A group of flamingos is called a 'flamboyance'.",
	"Honey never spoils. Archaeologists have eaten 3,000-year-old honey from Egyptian tombs.",
	"Octopuses have three hearts and blue blood.",
	"A day on Venus is longer than a year on Venus.",
	"Bananas are berries, but strawberries are not.",
	"The Eiffel Tower can grow up to 15 cm taller in summer as its iron expands in the heat.",
	"Sharks have existed longer than trees.",
	"There are more stars in the universe than grains of sand on Earth's beaches.",
	"A cloud can weigh more than a million pounds.",
	"Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
	"Wombat poop is cube-shaped.",
	"Oxford University is older than the Aztec Empire.",
	"A bolt of lightning is about five times hotter than the surface of the Sun.",
	"Pineapples take two years to grow.",
	"The dot over a lowercase 'i' or 'j' is called a tittle.",
	"Sea otters hold hands while sleeping so they don't drift apart.",
	"Sloths can hold their breath longer than dolphins can.",
	"The total length of the blood vessels in the human body is about 100,000 km.",
	"Bees can recognize human faces.",
	"Penguins propose to their mates with a pebble.",
	"A jiffy is an actual unit of time: 1/100th of a second.",
	"Hot water freezes faster than cold water in some conditions — the Mpemba effect.",
	"The unicorn is the national animal of Scotland.",
	"France was still executing people by guillotine when Star Wars came out (1977).",
	"There is a species of jellyfish that is biologically immortal.",
	"The shortest war in history lasted 38 to 45 minutes (Britain vs Zanzibar, 1896).",
	"Cows have best friends and get stressed when separated.",
	"Adult humans share about 60% of their DNA with bananas.",
	"The inventor of the Pringles can is buried in one.",
	"A group of porcupines is called a 'prickle'.",
	"Dolphins have names for each other.",
	"Earth's oceans contain enough salt to cover all the continents in a layer 500 ft thick.",
	"The first webcam was created to monitor a coffee pot at Cambridge University.",
	"Rabbits can't vomit.",
	"A Boeing 747's wingspan is longer than the Wright brothers' first flight distance.",
	"Human teeth are the only part of the body that can't heal themselves.",
	"The unicorn is Scotland's national animal. The thistle is just the emblem.",
	"The smell of freshly cut grass is actually a plant distress signal.",
	"Venus rotates backward compared to most other planets.",
	"The Twitter bird's official name is Larry.",
	"Polar bear skin is black; their fur is actually transparent.",
	"The longest English word without a vowel is 'rhythms'.",
	"Giraffes only need 5 to 30 minutes of sleep per day.",
	"The Mona Lisa has no eyebrows. It was fashionable to shave them off in Renaissance Florence.",
	"Earth's core is as hot as the Sun's surface.",
	"Cassette tapes are still selling more than 100 million units a year worldwide.",
	"The unicorn, the phoenix, and the griffin all appear on the Royal coat of arms of the United Kingdom.",
	"A hummingbird's heart beats up to 1,260 times per minute.",
	"The average person walks the equivalent of five times around the Earth in a lifetime.",
	"Chess has more possible games than atoms in the observable universe.",
	"The word 'robot' comes from a Czech word meaning 'forced labor'.",
];
